const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (s) => ipcRenderer.invoke('settings:save', s),
  saveScale: (s) => ipcRenderer.invoke('settings:scale', s),
  getAssets: () => ipcRenderer.invoke('asset:paths'),
  getAlarmMusicUrl: (id) => ipcRenderer.invoke('alarm:music-url', id),
  getRingingAlarm: () => ipcRenderer.invoke('alarm:ringing'),
  getMusicLibrary: () => ipcRenderer.invoke('music:library'),
  importMusic: () => ipcRenderer.invoke('music:import'),
  deleteMusic: (name) => ipcRenderer.invoke('music:delete', name),
  renameMusic: (oldName, newName) => ipcRenderer.invoke('music:rename', { oldName, newName }),
  getAutoStart: () => ipcRenderer.invoke('settings:getAutoStart'),
  setAutoStart: (v) => ipcRenderer.invoke('settings:setAutoStart', v),
  getWorkArea: () => ipcRenderer.invoke('win:workarea'),
  getBounds: () => ipcRenderer.invoke('win:bounds'),
  resizeWindow: (w, h) => ipcRenderer.send('win:resize', { width: w, height: h }),
  moveWindow: (x, y) => ipcRenderer.send('win:move', { x, y }),
  startDrag: (offX, offY) => ipcRenderer.send('drag:start', { offX, offY }),
  endDrag: () => ipcRenderer.send('drag:end'),
  dragBeat: () => ipcRenderer.send('drag:beat'),
  savePos: (right, bottom) => ipcRenderer.invoke('settings:pos', { right, bottom }),
  setIgnoreMouse: (b) => ipcRenderer.send('hit:ignore', b),
  openMenu: () => ipcRenderer.send('menu:open'),
  closeWindow: () => ipcRenderer.send('win:close'),
  stopAlarm: () => ipcRenderer.send('alarm:stop'),
  snoozeAlarm: () => ipcRenderer.send('alarm:snooze'),
  onAlarmState: (cb) => ipcRenderer.on('alarm:state', (_e, s) => cb(s)),
  onScaleReset: (cb) => ipcRenderer.on('scale:reset', () => cb()),
  onScaleChanged: (cb) => ipcRenderer.on('scale:changed', (_e, s) => cb(s)),
});
